-- MySQL Script generated by MySQL Workbench
-- Wed Oct 16 16:27:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`autoclave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autoclave` (
  `id` INT NOT NULL,
  `autoc_quantity` INT NULL,
  `autoc_heattime` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital_staff` (
  `id` INT NOT NULL,
  `hospsta_fname` VARCHAR(45) NULL,
  `hospsta_lname` VARCHAR(45) NULL,
  `hospsta_age` INT NULL,
  `hospsta_sex` VARCHAR(45) NULL,
  `hospsta_add` VARCHAR(45) NULL,
  `hospsta_licen` VARCHAR(45) NULL,
  `autoclave_autoc_id` INT NOT NULL,
  PRIMARY KEY (`id`, `autoclave_autoc_id`),
  INDEX `fk_HOSPITAL_STAFF_AUTOCLAVE1_idx` (`autoclave_autoc_id` ASC) VISIBLE,
  CONSTRAINT `fk_HOSPITAL_STAFF_AUTOCLAVE1`
    FOREIGN KEY (`autoclave_autoc_id`)
    REFERENCES `mydb`.`autoclave` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital` (
  `id` INT NOT NULL,
  `hosp_name` VARCHAR(45) NULL,
  `hosp_add` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_order` (
  `id` INT NOT NULL,
  `purchase_orderdate` DATE NULL,
  `purchase_datecomplete` INT NULL,
  `purchase_price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`office_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`office_staff` (
  `id` INT NOT NULL,
  `officesta_lname` VARCHAR(45) NULL,
  `officesta_fname` VARCHAR(45) NULL,
  `officesta_age` INT NULL,
  `officesta_addr` VARCHAR(45) NULL,
  `purchase_order_purchase_id` INT NOT NULL,
  PRIMARY KEY (`id`, `purchase_order_purchase_id`),
  INDEX `fk_OFFICE_STAFF_PURCHASE_ORDER1_idx` (`purchase_order_purchase_id` ASC) VISIBLE,
  CONSTRAINT `fk_OFFICE_STAFF_PURCHASE_ORDER1`
    FOREIGN KEY (`purchase_order_purchase_id`)
    REFERENCES `mydb`.`purchase_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`driver_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`driver_staff` (
  `id` INT NOT NULL,
  `driversta_lname` VARCHAR(45) NULL,
  `driversta_fname` VARCHAR(45) NULL,
  `driversta_age` INT NULL,
  `driversta_sex` VARCHAR(45) NULL,
  `driversta_add` VARCHAR(45) NULL,
  `driversta_licen` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materials` (
  `id` INT NOT NULL,
  `mater_name` VARCHAR(45) NULL,
  `mater_quantity` INT NULL,
  `mater_price` INT NULL,
  `driver staff_driversta_id` INT NOT NULL,
  `hospital_staff_hospsta_id` INT NOT NULL,
  `hospital_staff_autoclave_autoc_id` INT NOT NULL,
  `driver staff_driversta_id1` INT NOT NULL,
  `office_staff_officesta_id` INT NOT NULL,
  `office_staff_purchase_order_purchase_id` INT NOT NULL,
  `hospital_hosp_id` INT NOT NULL,
  `hospital_staff_hospsta_id1` INT NOT NULL,
  `hospital_staff_autoclave_autoc_id1` INT NOT NULL,
  `driver staff_driversta_id2` INT NOT NULL,
  `driver staff_driversta_id3` INT NOT NULL,
  `hospital_hosp_id1` INT NOT NULL,
  `office_staff_officesta_id1` INT NOT NULL,
  `office_staff_purchase_order_purchase_id1` INT NOT NULL,
  `driver_staff_driversta_id` INT NOT NULL,
  `driver_staff_driversta_id1` INT NOT NULL,
  `driver_staff_driversta_id2` INT NOT NULL,
  `driver_staff_driversta_id3` INT NOT NULL,
  PRIMARY KEY (`id`, `driver staff_driversta_id`, `hospital_staff_hospsta_id`, `hospital_staff_autoclave_autoc_id`, `driver staff_driversta_id1`, `office_staff_officesta_id`, `office_staff_purchase_order_purchase_id`, `hospital_hosp_id`, `hospital_staff_hospsta_id1`, `hospital_staff_autoclave_autoc_id1`, `driver staff_driversta_id2`, `driver staff_driversta_id3`, `hospital_hosp_id1`, `office_staff_officesta_id1`, `office_staff_purchase_order_purchase_id1`, `driver_staff_driversta_id`, `driver_staff_driversta_id1`, `driver_staff_driversta_id2`, `driver_staff_driversta_id3`),
  INDEX `fk_MATERIALS_HOSPITAL_STAFF1_idx` (`hospital_staff_hospsta_id1` ASC, `hospital_staff_autoclave_autoc_id1` ASC) VISIBLE,
  INDEX `fk_MATERIALS_HOSPITAL1_idx` (`hospital_hosp_id1` ASC) VISIBLE,
  INDEX `fk_MATERIALS_OFFICE_STAFF1_idx` (`office_staff_officesta_id1` ASC, `office_staff_purchase_order_purchase_id1` ASC) VISIBLE,
  INDEX `fk_MATERIALS_DRIVER_STAFF2_idx` (`driver_staff_driversta_id2` ASC) VISIBLE,
  INDEX `fk_MATERIALS_DRIVER_STAFF1_idx` (`driver_staff_driversta_id3` ASC) VISIBLE,
  CONSTRAINT `fk_MATERIALS_HOSPITAL_STAFF1`
    FOREIGN KEY (`hospital_staff_hospsta_id1` , `hospital_staff_autoclave_autoc_id1`)
    REFERENCES `mydb`.`hospital_staff` (`id` , `autoclave_autoc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIALS_HOSPITAL1`
    FOREIGN KEY (`hospital_hosp_id1`)
    REFERENCES `mydb`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIALS_OFFICE_STAFF1`
    FOREIGN KEY (`office_staff_officesta_id1` , `office_staff_purchase_order_purchase_id1`)
    REFERENCES `mydb`.`office_staff` (`id` , `purchase_order_purchase_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIALS_DRIVER_STAFF2`
    FOREIGN KEY (`driver_staff_driversta_id2`)
    REFERENCES `mydb`.`driver_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MATERIALS_DRIVER_STAFF1`
    FOREIGN KEY (`driver_staff_driversta_id3`)
    REFERENCES `mydb`.`driver_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company` (
  `id` INT NOT NULL,
  `comp_name` VARCHAR(45) NULL,
  `comp_addr` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fee` (
  `id` INT NOT NULL,
  `fee_date` DATE NULL,
  `fee_price` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient` (
  `id` INT NOT NULL,
  `pat_lname` VARCHAR(45) NULL,
  `pat_fname` VARCHAR(45) NULL,
  `pat_age` INT NULL,
  `pat_sex` VARCHAR(45) NULL,
  `pat_add` VARCHAR(45) NULL,
  `fee_fee_id` INT NOT NULL,
  `sales_invoice_invoice_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fee_fee_id`, `sales_invoice_invoice_id`),
  INDEX `fk_PATIENT_FEE1_idx` (`fee_fee_id` ASC) VISIBLE,
  CONSTRAINT `fk_PATIENT_FEE1`
    FOREIGN KEY (`fee_fee_id`)
    REFERENCES `mydb`.`fee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales_invoice` (
  `id` INT NOT NULL,
  `invoice_date` DATE NULL,
  `bonecements_quant` INT NULL,
  `bonecem_cost` INT NULL,
  `implants_quant` INT NULL,
  `implants_cost` INT NULL,
  `plates_quant` INT NULL,
  `plates_cost` INT NULL,
  `overall_cost` INT NULL,
  `patient_patient_id1` INT NOT NULL,
  `patient_fee_fee_id1` INT NOT NULL,
  `patient_sales_invoice_invoice_id1` INT NOT NULL,
  `patient_patient_id` INT NOT NULL,
  `patient_fee_fee_id` INT NOT NULL,
  `patient_sales_invoice_invoice_num` INT NOT NULL,
  PRIMARY KEY (`id`, `patient_patient_id1`, `patient_fee_fee_id1`, `patient_sales_invoice_invoice_id1`, `patient_patient_id`, `patient_fee_fee_id`, `patient_sales_invoice_invoice_num`),
  INDEX `fk_SALES_INVOICE_PATIENT2_idx` (`patient_patient_id1` ASC, `patient_fee_fee_id1` ASC, `patient_sales_invoice_invoice_id1` ASC) VISIBLE,
  INDEX `fk_SALES_INVOICE_PATIENT1_idx` (`patient_patient_id` ASC, `patient_fee_fee_id` ASC, `patient_sales_invoice_invoice_num` ASC) VISIBLE,
  CONSTRAINT `fk_SALES_INVOICE_PATIENT2`
    FOREIGN KEY (`patient_patient_id1` , `patient_fee_fee_id1` , `patient_sales_invoice_invoice_id1`)
    REFERENCES `mydb`.`patient` (`id` , `fee_fee_id` , `sales_invoice_invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SALES_INVOICE_PATIENT1`
    FOREIGN KEY (`patient_patient_id` , `patient_fee_fee_id` , `patient_sales_invoice_invoice_num`)
    REFERENCES `mydb`.`patient` (`id` , `fee_fee_id` , `sales_invoice_invoice_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assistant_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assistant_staff` (
  `id` INT NOT NULL,
  `assistantsta_lname` VARCHAR(45) NULL,
  `assistantsta_fname` VARCHAR(45) NULL,
  `assistantsta_licen` VARCHAR(45) NULL,
  `assistantsta_add` VARCHAR(45) NULL,
  `assistantsta_email` VARCHAR(45) NULL,
  `sales_invoice_invoice_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sales_invoice_invoice_id`),
  INDEX `fk_ASSISTANT_STAFF_SALES_INVOICE1_idx` (`sales_invoice_invoice_id` ASC) VISIBLE,
  CONSTRAINT `fk_ASSISTANT_STAFF_SALES_INVOICE1`
    FOREIGN KEY (`sales_invoice_invoice_id`)
    REFERENCES `mydb`.`sales_invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`operation` (
  `id` INT NOT NULL,
  `ope_patient` VARCHAR(45) NULL,
  `ope_hospital` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor` (
  `id` INT NOT NULL,
  `doc_lname` VARCHAR(45) NULL,
  `doc_fname` VARCHAR(45) NULL,
  `doc_licen` VARCHAR(45) NULL,
  `doc_hosp` VARCHAR(45) NULL,
  `doc_addr` VARCHAR(45) NULL,
  `doc_email` VARCHAR(45) NULL,
  `materials_mater_num` INT NOT NULL,
  `company_comp_id` INT NOT NULL,
  `office_staff_officesta_id` INT NOT NULL,
  `company_comp_id1` INT NOT NULL,
  `assistant_staff_assiststa_id` INT NOT NULL,
  `assistant_staff_assiststa_id1` INT NOT NULL,
  `operation_operation_room_num` INT NOT NULL,
  `office_staff_officesta_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `materials_mater_num`, `company_comp_id`, `office_staff_officesta_id`, `company_comp_id1`, `assistant_staff_assiststa_id`, `assistant_staff_assiststa_id1`, `operation_operation_room_num`, `office_staff_officesta_id1`),
  INDEX `fk_DOCTOR_COMPANY1_idx` (`company_comp_id1` ASC) VISIBLE,
  INDEX `fk_DOCTOR_ASSISTANT_STAFF1_idx` (`assistant_staff_assiststa_id` ASC) VISIBLE,
  INDEX `fk_DOCTOR_ASSISTANT_STAFF2_idx` (`assistant_staff_assiststa_id1` ASC) VISIBLE,
  INDEX `fk_DOCTOR_OPERATION1_idx` (`operation_operation_room_num` ASC) VISIBLE,
  INDEX `fk_DOCTOR_OFFICE_STAFF1_idx` (`office_staff_officesta_id1` ASC) VISIBLE,
  CONSTRAINT `fk_DOCTOR_COMPANY1`
    FOREIGN KEY (`company_comp_id1`)
    REFERENCES `mydb`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_ASSISTANT_STAFF1`
    FOREIGN KEY (`assistant_staff_assiststa_id`)
    REFERENCES `mydb`.`assistant_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_ASSISTANT_STAFF2`
    FOREIGN KEY (`assistant_staff_assiststa_id1`)
    REFERENCES `mydb`.`assistant_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_OPERATION1`
    FOREIGN KEY (`operation_operation_room_num`)
    REFERENCES `mydb`.`operation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_OFFICE_STAFF1`
    FOREIGN KEY (`office_staff_officesta_id1`)
    REFERENCES `mydb`.`office_staff` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR_has_MATERIALS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR_has_MATERIALS` (
  `DOCTOR_DOC_ID` INT NOT NULL,
  `DOCTOR_MATERIALS_MATER_NUM` INT NOT NULL,
  `MATERIALS_MATER_NUM` INT NOT NULL,
  PRIMARY KEY (`DOCTOR_DOC_ID`, `DOCTOR_MATERIALS_MATER_NUM`, `MATERIALS_MATER_NUM`),
  INDEX `fk_DOCTOR_has_MATERIALS_MATERIALS1_idx` (`MATERIALS_MATER_NUM` ASC) VISIBLE,
  INDEX `fk_DOCTOR_has_MATERIALS_DOCTOR1_idx` (`DOCTOR_DOC_ID` ASC, `DOCTOR_MATERIALS_MATER_NUM` ASC) VISIBLE,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS_DOCTOR1`
    FOREIGN KEY (`DOCTOR_DOC_ID` , `DOCTOR_MATERIALS_MATER_NUM`)
    REFERENCES `mydb`.`doctor` (`id` , `materials_mater_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS_MATERIALS1`
    FOREIGN KEY (`MATERIALS_MATER_NUM`)
    REFERENCES `mydb`.`materials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_recieves_materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor_recieves_materials` (
  `id` INT NOT NULL,
  `doctor_materials_mater_num` INT NOT NULL,
  `doctor_company_comp_id` INT NOT NULL,
  `doctor_office_staff_officesta_id` INT NOT NULL,
  `doctor_company_comp_id1` INT NOT NULL,
  `materials_mater_num` INT NOT NULL,
  `materials_driver staff_driversta_id` INT NOT NULL,
  `materials_hospital_staff_hospsta_id` INT NOT NULL,
  `materials_hospital_staff_autoclave_autoc_num` INT NOT NULL,
  `materials_driver staff_driversta_id1` INT NOT NULL,
  `materials_office_staff_officesta_id` INT NOT NULL,
  `materials_office_staff_purchase_order_purchase_id` INT NOT NULL,
  `materials_hospital_hosp_id` INT NOT NULL,
  `materials_hospital_staff_hospsta_id1` INT NOT NULL,
  `materials_hospital_staff_autoclave_autoc_num1` INT NOT NULL,
  `materials_driver staff_driversta_id2` INT NOT NULL,
  PRIMARY KEY (`id`, `doctor_materials_mater_num`, `doctor_company_comp_id`, `doctor_office_staff_officesta_id`, `doctor_company_comp_id1`, `materials_mater_num`, `materials_driver staff_driversta_id`, `materials_hospital_staff_hospsta_id`, `materials_hospital_staff_autoclave_autoc_num`, `materials_driver staff_driversta_id1`, `materials_office_staff_officesta_id`, `materials_office_staff_purchase_order_purchase_id`, `materials_hospital_hosp_id`, `materials_hospital_staff_hospsta_id1`, `materials_hospital_staff_autoclave_autoc_num1`, `materials_driver staff_driversta_id2`),
  INDEX `fk_DOCTOR_has_MATERIALS1_MATERIALS1_idx` (`materials_mater_num` ASC, `materials_driver staff_driversta_id` ASC, `materials_hospital_staff_hospsta_id` ASC, `materials_hospital_staff_autoclave_autoc_num` ASC, `materials_driver staff_driversta_id1` ASC, `materials_office_staff_officesta_id` ASC, `materials_office_staff_purchase_order_purchase_id` ASC, `materials_hospital_hosp_id` ASC, `materials_hospital_staff_hospsta_id1` ASC, `materials_hospital_staff_autoclave_autoc_num1` ASC, `materials_driver staff_driversta_id2` ASC) VISIBLE,
  INDEX `fk_DOCTOR_has_MATERIALS1_DOCTOR1_idx` (`id` ASC, `doctor_materials_mater_num` ASC, `doctor_company_comp_id` ASC, `doctor_office_staff_officesta_id` ASC, `doctor_company_comp_id1` ASC) VISIBLE,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS1_DOCTOR1`
    FOREIGN KEY (`id` , `doctor_materials_mater_num` , `doctor_company_comp_id` , `doctor_office_staff_officesta_id` , `doctor_company_comp_id1`)
    REFERENCES `mydb`.`doctor` (`id` , `materials_mater_num` , `company_comp_id` , `office_staff_officesta_id` , `company_comp_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS1_MATERIALS1`
    FOREIGN KEY (`materials_mater_num` , `materials_driver staff_driversta_id` , `materials_hospital_staff_hospsta_id` , `materials_hospital_staff_autoclave_autoc_num` , `materials_driver staff_driversta_id1` , `materials_office_staff_officesta_id` , `materials_office_staff_purchase_order_purchase_id` , `materials_hospital_hosp_id` , `materials_hospital_staff_hospsta_id1` , `materials_hospital_staff_autoclave_autoc_num1` , `materials_driver staff_driversta_id2`)
    REFERENCES `mydb`.`materials` (`id` , `driver staff_driversta_id` , `hospital_staff_hospsta_id` , `hospital_staff_autoclave_autoc_id` , `driver staff_driversta_id1` , `office_staff_officesta_id` , `office_staff_purchase_order_purchase_id` , `hospital_hosp_id` , `hospital_staff_hospsta_id1` , `hospital_staff_autoclave_autoc_id1` , `driver staff_driversta_id2`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doctor_operates_patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor_operates_patient` (
  `id` INT NOT NULL,
  `doctor_materials_mater_id` INT NOT NULL,
  `doctor_company_comp_id` INT NOT NULL,
  `doctor_office_staff_officesta_id` INT NOT NULL,
  `doctor_company_comp_id1` INT NOT NULL,
  `doctor_assistant_staff_assiststa_id` INT NOT NULL,
  `patient_patient_id` INT NOT NULL,
  PRIMARY KEY (`id`, `doctor_materials_mater_id`, `doctor_company_comp_id`, `doctor_office_staff_officesta_id`, `doctor_company_comp_id1`, `doctor_assistant_staff_assiststa_id`, `patient_patient_id`),
  INDEX `fk_DOCTOR_has_PATIENT_PATIENT1_idx` (`patient_patient_id` ASC) VISIBLE,
  INDEX `fk_DOCTOR_has_PATIENT_DOCTOR1_idx` (`id` ASC, `doctor_materials_mater_id` ASC, `doctor_company_comp_id` ASC, `doctor_office_staff_officesta_id` ASC, `doctor_company_comp_id1` ASC, `doctor_assistant_staff_assiststa_id` ASC) VISIBLE,
  CONSTRAINT `fk_DOCTOR_has_PATIENT_DOCTOR1`
    FOREIGN KEY (`id` , `doctor_materials_mater_id` , `doctor_company_comp_id` , `doctor_office_staff_officesta_id` , `doctor_company_comp_id1` , `doctor_assistant_staff_assiststa_id`)
    REFERENCES `mydb`.`doctor` (`id` , `materials_mater_num` , `company_comp_id` , `office_staff_officesta_id` , `company_comp_id1` , `assistant_staff_assiststa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_has_PATIENT_PATIENT1`
    FOREIGN KEY (`patient_patient_id`)
    REFERENCES `mydb`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR_RECIEVES_MATERIALS1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR_RECIEVES_MATERIALS1` (
  `DOCTOR_DOC_ID` INT NOT NULL,
  `DOCTOR_MATERIALS_MATER_NUM` INT NOT NULL,
  `DOCTOR_COMPANY_COMP_ID` INT NOT NULL,
  `DOCTOR_OFFICE_STAFF_OFFICESTA_ID` INT NOT NULL,
  `DOCTOR_COMPANY_COMP_ID1` INT NOT NULL,
  `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID` INT NOT NULL,
  `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1` INT NOT NULL,
  `DOCTOR_OPERATION_OPERATION_ROOM_NUM` INT NOT NULL,
  `MATERIALS_MATER_NUM` INT NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM` INT NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1` INT NOT NULL,
  `MATERIALS_OFFICE_STAFF_OFFICESTA_ID` INT NOT NULL,
  `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_HOSP_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1` INT NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2` INT NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3` INT NOT NULL,
  PRIMARY KEY (`DOCTOR_DOC_ID`, `DOCTOR_MATERIALS_MATER_NUM`, `DOCTOR_COMPANY_COMP_ID`, `DOCTOR_OFFICE_STAFF_OFFICESTA_ID`, `DOCTOR_COMPANY_COMP_ID1`, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID`, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1`, `DOCTOR_OPERATION_OPERATION_ROOM_NUM`, `MATERIALS_MATER_NUM`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID`, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID`, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1`, `MATERIALS_OFFICE_STAFF_OFFICESTA_ID`, `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID`, `MATERIALS_HOSPITAL_HOSP_ID`, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1`, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3`),
  INDEX `fk_DOCTOR_has_MATERIALS1_MATERIALS2_idx` (`MATERIALS_MATER_NUM` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID` ASC, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID` ASC, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1` ASC, `MATERIALS_OFFICE_STAFF_OFFICESTA_ID` ASC, `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID` ASC, `MATERIALS_HOSPITAL_HOSP_ID` ASC, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1` ASC, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3` ASC) VISIBLE,
  INDEX `fk_DOCTOR_has_MATERIALS1_DOCTOR2_idx` (`DOCTOR_DOC_ID` ASC, `DOCTOR_MATERIALS_MATER_NUM` ASC, `DOCTOR_COMPANY_COMP_ID` ASC, `DOCTOR_OFFICE_STAFF_OFFICESTA_ID` ASC, `DOCTOR_COMPANY_COMP_ID1` ASC, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID` ASC, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1` ASC, `DOCTOR_OPERATION_OPERATION_ROOM_NUM` ASC) VISIBLE,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS1_DOCTOR2`
    FOREIGN KEY (`DOCTOR_DOC_ID` , `DOCTOR_MATERIALS_MATER_NUM` , `DOCTOR_COMPANY_COMP_ID` , `DOCTOR_OFFICE_STAFF_OFFICESTA_ID` , `DOCTOR_COMPANY_COMP_ID1` , `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID` , `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1` , `DOCTOR_OPERATION_OPERATION_ROOM_NUM`)
    REFERENCES `mydb`.`doctor` (`id` , `materials_mater_num` , `company_comp_id` , `office_staff_officesta_id` , `company_comp_id1` , `assistant_staff_assiststa_id` , `assistant_staff_assiststa_id1` , `operation_operation_room_num`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS1_MATERIALS2`
    FOREIGN KEY (`MATERIALS_MATER_NUM` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID` , `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID` , `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1` , `MATERIALS_OFFICE_STAFF_OFFICESTA_ID` , `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID` , `MATERIALS_HOSPITAL_HOSP_ID` , `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1` , `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3`)
    REFERENCES `mydb`.`materials` (`id` , `driver staff_driversta_id` , `hospital_staff_hospsta_id` , `hospital_staff_autoclave_autoc_id` , `driver staff_driversta_id1` , `office_staff_officesta_id` , `office_staff_purchase_order_purchase_id` , `hospital_hosp_id` , `hospital_staff_hospsta_id1` , `hospital_staff_autoclave_autoc_id1` , `driver staff_driversta_id2` , `driver staff_driversta_id3`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DOCTOR_has_MATERIALS1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DOCTOR_has_MATERIALS1` (
  `DOCTOR_DOC_ID` INT NOT NULL,
  `DOCTOR_MATERIALS_MATER_NUM` INT NOT NULL,
  `DOCTOR_COMPANY_COMP_ID` INT NOT NULL,
  `DOCTOR_OFFICE_STAFF_OFFICESTA_ID` INT NOT NULL,
  `DOCTOR_COMPANY_COMP_ID1` INT NOT NULL,
  `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID` INT NOT NULL,
  `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1` INT NOT NULL,
  `DOCTOR_OPERATION_OPERATION_ROOM_NUM` INT NOT NULL,
  `DOCTOR_OFFICE_STAFF_OFFICESTA_ID1` INT NOT NULL,
  `MATERIALS_MATER_NAME` VARCHAR(45) NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM` INT NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1` INT NOT NULL,
  `MATERIALS_OFFICE_STAFF_OFFICESTA_ID` INT NOT NULL,
  `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_HOSP_ID` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1` INT NOT NULL,
  `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1` INT NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2` INT NOT NULL,
  `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3` INT NOT NULL,
  `MATERIALS_HOSPITAL_HOSP_ID1` INT NOT NULL,
  `MATERIALS_OFFICE_STAFF_OFFICESTA_ID1` INT NOT NULL,
  `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID1` INT NOT NULL,
  `MATERIALS_DRIVER_STAFF_DRIVERSTA_ID` INT NOT NULL,
  PRIMARY KEY (`DOCTOR_DOC_ID`, `DOCTOR_MATERIALS_MATER_NUM`, `DOCTOR_COMPANY_COMP_ID`, `DOCTOR_OFFICE_STAFF_OFFICESTA_ID`, `DOCTOR_COMPANY_COMP_ID1`, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID`, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1`, `DOCTOR_OPERATION_OPERATION_ROOM_NUM`, `DOCTOR_OFFICE_STAFF_OFFICESTA_ID1`, `MATERIALS_MATER_NAME`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID`, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID`, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1`, `MATERIALS_OFFICE_STAFF_OFFICESTA_ID`, `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID`, `MATERIALS_HOSPITAL_HOSP_ID`, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1`, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2`, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3`, `MATERIALS_HOSPITAL_HOSP_ID1`, `MATERIALS_OFFICE_STAFF_OFFICESTA_ID1`, `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID1`, `MATERIALS_DRIVER_STAFF_DRIVERSTA_ID`),
  INDEX `fk_DOCTOR_has_MATERIALS1_MATERIALS3_idx` (`MATERIALS_MATER_NAME` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID` ASC, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID` ASC, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1` ASC, `MATERIALS_OFFICE_STAFF_OFFICESTA_ID` ASC, `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID` ASC, `MATERIALS_HOSPITAL_HOSP_ID` ASC, `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1` ASC, `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2` ASC, `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3` ASC, `MATERIALS_HOSPITAL_HOSP_ID1` ASC, `MATERIALS_OFFICE_STAFF_OFFICESTA_ID1` ASC, `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID1` ASC, `MATERIALS_DRIVER_STAFF_DRIVERSTA_ID` ASC) VISIBLE,
  INDEX `fk_DOCTOR_has_MATERIALS1_DOCTOR3_idx` (`DOCTOR_DOC_ID` ASC, `DOCTOR_MATERIALS_MATER_NUM` ASC, `DOCTOR_COMPANY_COMP_ID` ASC, `DOCTOR_OFFICE_STAFF_OFFICESTA_ID` ASC, `DOCTOR_COMPANY_COMP_ID1` ASC, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID` ASC, `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1` ASC, `DOCTOR_OPERATION_OPERATION_ROOM_NUM` ASC, `DOCTOR_OFFICE_STAFF_OFFICESTA_ID1` ASC) VISIBLE,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS1_DOCTOR3`
    FOREIGN KEY (`DOCTOR_DOC_ID` , `DOCTOR_MATERIALS_MATER_NUM` , `DOCTOR_COMPANY_COMP_ID` , `DOCTOR_OFFICE_STAFF_OFFICESTA_ID` , `DOCTOR_COMPANY_COMP_ID1` , `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID` , `DOCTOR_ASSISTANT_STAFF_ASSISTSTA_ID1` , `DOCTOR_OPERATION_OPERATION_ROOM_NUM` , `DOCTOR_OFFICE_STAFF_OFFICESTA_ID1`)
    REFERENCES `mydb`.`doctor` (`id` , `materials_mater_num` , `company_comp_id` , `office_staff_officesta_id` , `company_comp_id1` , `assistant_staff_assiststa_id` , `assistant_staff_assiststa_id1` , `operation_operation_room_num` , `office_staff_officesta_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DOCTOR_has_MATERIALS1_MATERIALS3`
    FOREIGN KEY (`MATERIALS_MATER_NAME` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID` , `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID` , `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID1` , `MATERIALS_OFFICE_STAFF_OFFICESTA_ID` , `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID` , `MATERIALS_HOSPITAL_HOSP_ID` , `MATERIALS_HOSPITAL_STAFF_HOSPSTA_ID1` , `MATERIALS_HOSPITAL_STAFF_AUTOCLAVE_AUTOC_NUM1` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID2` , `MATERIALS_DRIVER STAFF_DRIVERSTA_ID3` , `MATERIALS_HOSPITAL_HOSP_ID1` , `MATERIALS_OFFICE_STAFF_OFFICESTA_ID1` , `MATERIALS_OFFICE_STAFF_PURCHASE_ORDER_PURCHASE_ID1` , `MATERIALS_DRIVER_STAFF_DRIVERSTA_ID`)
    REFERENCES `mydb`.`materials` (`id` , `driver staff_driversta_id` , `hospital_staff_hospsta_id` , `hospital_staff_autoclave_autoc_id` , `driver staff_driversta_id1` , `office_staff_officesta_id` , `office_staff_purchase_order_purchase_id` , `hospital_hosp_id` , `hospital_staff_hospsta_id1` , `hospital_staff_autoclave_autoc_id1` , `driver staff_driversta_id2` , `driver staff_driversta_id3` , `hospital_hosp_id1` , `office_staff_officesta_id1` , `office_staff_purchase_order_purchase_id1` , `driver_staff_driversta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
